sudo: required
language: node_js
os: osx
services:
    - docker
before_install:
    - docker build -f Dockerfile.dev -t whoispankaj/docker-react .

script:
    - docker run -e CI=true whoispankaj/docker-react npm run test -- --coverage